# Generated by Django 5.2.1 on 2025-07-09 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(choices=[('dr-joao', 'Dr. João Silva'), ('dra-maria', 'Dra. Maria Santos'), ('dr-pedro', 'Dr. Pedro Costa'), ('dra-ana', 'Dra. Ana Lima')])),
                ('especialidade', models.CharField(blank=True, choices=[('cardiologia', 'Cardiologia'), ('geriatria', 'Geriatria'), ('clinicogeral', 'Clínico Geral'), ('oftalmologia', 'Oftalmologia')], null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('emergencia', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='Baixa')),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('concluido', 'Concluido')], default='Solicitado')),
                ('data_solicitacao', models.DateField(auto_now=True)),
                ('data_agendamento', models.DateField()),
                ('hora_agendamento', models.CharField(choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')])),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now=True)),
                ('f_cardiaca', models.IntegerField(blank=True, null=True, verbose_name='Frequência Cardíaca')),
                ('glicemia', models.IntegerField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('p_sistolica', models.IntegerField(blank=True, null=True, verbose_name='Pressão Sistolica')),
                ('p_diastolica', models.IntegerField(blank=True, null=True, verbose_name='Pressão Diastolica')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('p_nome', models.CharField(max_length=64, verbose_name='Primeiro Nome')),
                ('sobrenome', models.CharField(max_length=64)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')])),
                ('foto_perfil', models.ImageField(default='default.jpg', upload_to='perfis/')),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=255)),
                ('saude', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.registrosaude')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
